"""add weather_code to observations and forecasts

Revision ID: a98b81fcea6b
Revises: 54cfa3b224e3
Create Date: 2026-07-28 10:31:01.211131
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a98b81fcea6b"
down_revision: str | None = "54cfa3b224e3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("forecasts", sa.Column("weather_code", sa.Integer(), nullable=True))
    op.add_column(
        "observations", sa.Column("weather_code", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("observations", "weather_code")
    op.drop_column("forecasts", "weather_code")
    # ### end Alembic commands ###
